# Generated by Django 5.2.16 on 2026-07-15 12:28

import django.db.models.deletion
from django.db import migrations, models

def seed_permissions_and_roles(apps, schema_editor):
    SystemPermission = apps.get_model('users', 'SystemPermission')
    CustomRole = apps.get_model('users', 'CustomRole')
    User = apps.get_model('users', 'User')

    # Seed SystemPermissions
    permissions_data = [
        # Projects Module
        {'module': 'projects', 'codename': 'create_project', 'name': 'Create Projects'},
        {'module': 'projects', 'codename': 'edit_project', 'name': 'Edit Projects'},
        {'module': 'projects', 'codename': 'delete_project', 'name': 'Delete Projects'},
        {'module': 'projects', 'codename': 'mark_complete_project', 'name': 'Mark Project as Complete'},
        # Tasks Module
        {'module': 'tasks', 'codename': 'create_task', 'name': 'Create Tasks'},
        {'module': 'tasks', 'codename': 'edit_task', 'name': 'Edit Tasks'},
        {'module': 'tasks', 'codename': 'delete_task', 'name': 'Delete Tasks'},
        # User Management Module
        {'module': 'users', 'codename': 'manage_users', 'name': 'Manage Users'},
        {'module': 'users', 'codename': 'manage_roles', 'name': 'Manage Roles'},
    ]

    perms = {}
    for p in permissions_data:
        obj, _ = SystemPermission.objects.get_or_create(
            codename=p['codename'],
            defaults={'module': p['module'], 'name': p['name']}
        )
        perms[p['codename']] = obj

    # Seed CustomRoles
    admin_role, _ = CustomRole.objects.get_or_create(name='ADMIN')
    admin_role.permissions.set(list(perms.values()))

    pm_role, _ = CustomRole.objects.get_or_create(name='PM')
    pm_role.permissions.set([
        perms['create_project'],
        perms['edit_project'],
        perms['mark_complete_project'],
        perms['create_task'],
        perms['edit_task'],
        perms['delete_task'],
    ])

    dev_role, _ = CustomRole.objects.get_or_create(name='DEVELOPER')
    dev_role.permissions.set([
        perms['edit_task'],
    ])

    # Migrate user roles from string to foreign keys
    for user in User.objects.all():
        old_role = getattr(user, 'role_old', '')
        if old_role == 'ADMIN':
            user.role = admin_role
        elif old_role == 'PM':
            user.role = pm_role
        else:
            user.role = dev_role
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50)),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='role_old',
        ),
        migrations.AddField(
            model_name='user',
            name='is_permissions_customized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customrole'),
        ),
        migrations.AddField(
            model_name='customrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='users.systempermission'),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_permissions',
            field=models.ManyToManyField(blank=True, related_name='override_users', to='users.systempermission'),
        ),
        migrations.RunPython(seed_permissions_and_roles),
        migrations.RemoveField(
            model_name='user',
            name='role_old',
        ),
    ]
