# Generated by Django 5.2.16 on 2026-07-15 12:28

from django.db import migrations, models

def link_existing_projects_to_default_statuses(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    TaskStatus = apps.get_model('tasks', 'TaskStatus')

    try:
        todo_status = TaskStatus.objects.get(name='TODO')
        inprogress_status = TaskStatus.objects.get(name='IN_PROGRESS')
        done_status = TaskStatus.objects.get(name='DONE')

        for project in Project.objects.all():
            project.statuses.add(todo_status, inprogress_status, done_status)
    except TaskStatus.DoesNotExist:
        # If running in a test suite or clean db where statuses aren't created yet, ignore
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_status'),
        ('tasks', '0003_taskstatus_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='statuses',
            field=models.ManyToManyField(blank=True, related_name='projects', to='tasks.taskstatus'),
        ),
        migrations.RunPython(link_existing_projects_to_default_statuses),
    ]
