# Generated by Django 5.2.16 on 2026-07-15 12:28

import django.db.models.deletion
from django.db import migrations, models

def seed_task_statuses(apps, schema_editor):
    TaskStatus = apps.get_model('tasks', 'TaskStatus')
    Task = apps.get_model('tasks', 'Task')

    todo_status, _ = TaskStatus.objects.get_or_create(name='TODO')
    inprogress_status, _ = TaskStatus.objects.get_or_create(name='IN_PROGRESS')
    done_status, _ = TaskStatus.objects.get_or_create(name='DONE')

    for task in Task.objects.all():
        old_status = getattr(task, 'status_old', '')
        if old_status == 'IN_PROGRESS':
            task.status = inprogress_status
        elif old_status == 'DONE':
            task.status = done_status
        else:
            task.status = todo_status
        task.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='status_old',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='tasks.taskstatus'),
        ),
        migrations.RunPython(seed_task_statuses),
        migrations.RemoveField(
            model_name='task',
            name='status_old',
        ),
    ]
